[tool.poetry]
name = "pikaraoke"
version = "1.0.0"
description = "Youtube-based Karaoke machine for Raspberry Pi, OSX, Windows, and Linux"
authors = ["Marius <my_email@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
CherryPy = "18.10.0"
Flask = "2.2.5"
qrcode = "7.4.2"
psutil = "6.0.0"
unidecode = "1.3.8"
requests = "2.32.3"
flask-paginate = "2021.10.29"
jinja2 = "3.0.3"  # Avoid escape issue: https://github.com/sphinx-doc/sphinx/issues/10289
Babel = "2.9.1"
Flask-Babel = "2.0.0"
selenium = "4.22.0"
ffmpeg-python = "0.2.0"
yt-dlp = "2024.7.9"

[tool.poetry.dev-dependencies]
pre-commit = "3.7.1"
pytest = "8.2.2"
pytest-playwright = "0.5.1"
pytest-xdist = "3.6.1"
pillow = "10.4.0"
requests = "2.32.3"
qrcode = "7.4.2"
pyzbar = "0.1.9"


[tool.poetry.scripts]
pikaraoke = "pikaraoke.app:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
